In [31]:
import pandas as pd
df = pd.read_csv('yelp_labelled.txt', names=['sentence', 'label'], sep='\t')

In [32]:
df.tail()

sentence  label
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

In [33]:
from sklearn.model_selection import train_test_split
kalimat = df['sentence'].values
y = df['label'].values
kalimat_latih, kalimat_test, y_latih, y_test = train_test_split(kalimat, y, test_size=0.2)

In [34]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
 
tokenizer = Tokenizer(num_words=250, oov_token='x')
tokenizer.fit_on_texts(kalimat_latih) 
tokenizer.fit_on_texts(kalimat_test)
 
sekuens_latih = tokenizer.texts_to_sequences(kalimat_latih)
sekuens_test = tokenizer.texts_to_sequences(kalimat_test)
 
padded_latih = pad_sequences(sekuens_latih, maxlen=20) 
padded_test = pad_sequences(sekuens_test, maxlen=20)
print(padded_latih)

[[  1  38  10 ...   6  17 152]
 [  0   0   0 ...  18   3  12]
 [  0   0   0 ... 202  28   1]
 ...
 [  0  51  33 ...  16  14  33]
 [  1   1  31 ...   2  12   1]
 [  0   0   0 ...   8  55   1]]


In [35]:
import tensorflow as tf
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(250, 16, input_length=20),
    # tf.keras.layers.LSTM(64),
    tf.keras.layers.GlobalAveragePooling1D(),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(1, activation='sigmoid')
])
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [36]:
num_epochs = 100
history = model.fit(padded_latih, y_latih, epochs=num_epochs, 
                    validation_data=(padded_test, y_test), verbose=2)

Epoch 1/100
25/25 - 1s - loss: 0.6930 - accuracy: 0.4988 - val_loss: 0.6928 - val_accuracy: 0.5150 - 1s/epoch - 51ms/step
Epoch 2/100
25/25 - 0s - loss: 0.6905 - accuracy: 0.5387 - val_loss: 0.6920 - val_accuracy: 0.5350 - 146ms/epoch - 6ms/step
Epoch 3/100
25/25 - 0s - loss: 0.6852 - accuracy: 0.5800 - val_loss: 0.6873 - val_accuracy: 0.5350 - 147ms/epoch - 6ms/step
Epoch 4/100
25/25 - 0s - loss: 0.6737 - accuracy: 0.6150 - val_loss: 0.6778 - val_accuracy: 0.5650 - 127ms/epoch - 5ms/step
Epoch 5/100
25/25 - 0s - loss: 0.6518 - accuracy: 0.6737 - val_loss: 0.6617 - val_accuracy: 0.5750 - 121ms/epoch - 5ms/step
Epoch 6/100
25/25 - 0s - loss: 0.6157 - accuracy: 0.7025 - val_loss: 0.6318 - val_accuracy: 0.6600 - 152ms/epoch - 6ms/step
Epoch 7/100
25/25 - 0s - loss: 0.5620 - accuracy: 0.7638 - val_loss: 0.6027 - val_accuracy: 0.6850 - 218ms/epoch - 9ms/step
Epoch 8/100
25/25 - 0s - loss: 0.5003 - accuracy: 0.7962 - val_loss: 0.5748 - val_accuracy: 0.6950 - 330ms/epoch - 13ms/step
Epoch 9/1